### ISSUE TITLE
HEC-RAS Output DSS filename can be incorrect depending on model setup. 

### ISSUE THREAD

**Issue by Rmccal** [waterinstitute/EnDMC_Desktop#14]
There are a number of ways to define the output DSS filename used by the plans files in HEC-RAS. The default is to use the model name appended with .DSS. This is the one currently used as the output in the EnDMC_Desktop. While testing with a model (AA_Atchafalaya_Ri) 
 which is setup to output to a different DSS file, I noticed that the JSON files did not output the correct output file. In this case there was not a AA_Atchafalaya_Ri.DSS file in the model data at all. 

There are 3 options to name the output files for each plan. 
1. The default DSS file as above
2. Use the plan name as the DSS filename 
3. Use a unique user specified DSS filename

The DSS filename used is specified within the plan file (*.Pxx) on the line with "DSS File=" like below:
DSS File=.\GustavIke_2008_Calibration\GustavIke_2008_Calibration.dss
Let me know if you have any questions

**Comment by mylesmc123** [comment]
Thank you for the detailed issue. We will get this addressed.
