### ISSUE TITLE
Additional inputs for plan file JSON that may want to include.

### ISSUE THREAD

**Issue by Rmccal** [waterinstitute/EnDMC_Desktop#15]
Looking at the Plan JSON files I noticed that the terrain input from Mapper is included, but the Manning's n, infiltration, % impervious, and Sediment bed material layers are not included. This seems to be the last few pieces missing to have a complete accounting of all inputs to the plans.  These are all important inputs into the plans which may have multiple versions depending on the model setup. So would be good to know what is used for each plan. Note that not all of these are necessarily in each plan but can be configured in Mapper for each plan.
Let me know if you have any questions. 

Ric

**Comment by mylesmc123** [comment]
Thank you @Rmccal. Totally agree!

**Comment by mylesmc123** [comment]
> Looking at the Plan JSON files I noticed that the terrain input from Mapper is included, but the Manning's n, infiltration, % impervious, and Sediment bed material layers are not included. This seems to be the last few pieces missing to have a complete accounting of all inputs to the plans. These are all important inputs into the plans which may have multiple versions depending on the model setup. So would be good to know what is used for each plan. Note that not all of these are necessarily in each plan but can be configured in Mapper for each plan. Let me know if you have any questions.
> 
> Ric

@Rmccal Do you have a sediment bed material layer example? Is there a model that uses this layer on the LWI AWS S3 by chance? If so, which plan number is it?
