### ISSUE TITLE
HMS parser throws variable error

### ISSUE THREAD

**Issue by openSourcerer9000** [waterinstitute/EnDMC_Desktop#17]
Just like it says:

![image](https://github.com/waterinstitute/EnDMC_Desktop/assets/61931826/419df44e-df82-406d-832b-50242d87f29c)

**Comment by mylesmc123** [comment]
Thanks Sean @openSourcerer9000 ! I'll touch base with you on using a new release to see if it fixes this problem.

**Comment by mylesmc123** [comment]
Issue was that any input field that was surrounded in quotes caused an error. Added more robust sanitization of input fields from the GUI. Fixed in Release v2.2
